# Generated by Django 6.0.4 on 2026-05-15 12:07

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0006_module_userprofile_allowed_modules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_global_2fa', models.BooleanField(default=True, help_text='If checked, all users must verify via 2FA. If unchecked, 2FA is skipped.', verbose_name='Enable Global 2FA')),
            ],
            options={
                'verbose_name': 'Global Setting',
                'verbose_name_plural': 'Global Settings',
            },
        ),
        migrations.CreateModel(
            name='SMSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cost_per_sms', models.DecimalField(decimal_places=2, default=100.0, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_back_dating', models.BooleanField(default=False, help_text='If enabled, Manually set dates for deposits and repayments can be used.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('income', 'Income'), ('expense', 'Expense'), ('equity', 'Equity')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.chartofaccount')),
            ],
            options={
                'verbose_name': 'Chart of Account',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_reference', models.CharField(blank=True, help_text='Unique alphanumeric loan reference (e.g., LN-ABC1234567)', max_length=20, null=True, unique=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Percentage rate (e.g., 12.5)', max_digits=5)),
                ('period_months', models.IntegerField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('disbursed_date', models.DateField(blank=True, null=True)),
                ('total_payable', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('principal_balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('interest_balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('product_type', models.CharField(choices=[('personal', 'Personal Loan'), ('business', 'Business Loan'), ('salary', 'Salary Advance'), ('group', 'Group Loan'), ('emergency', 'Emergency Loan'), ('asset', 'Asset Finance')], default='personal', max_length=20, verbose_name='Loan Product')),
                ('purpose', models.TextField(blank=True, null=True, verbose_name='Loan Purpose / Description')),
                ('guarantor_1_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Guarantor 1 Name')),
                ('guarantor_1_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Guarantor 1 Phone')),
                ('guarantor_2_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Guarantor 2 Name')),
                ('guarantor_2_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Guarantor 2 Phone')),
                ('collateral_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Collateral Type')),
                ('collateral_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Estimated Collateral Value')),
                ('collateral_description', models.TextField(blank=True, null=True, verbose_name='Collateral Details')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Business / Physical Location')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Person')),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Phone Number')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('arrears', 'In Arrears'), ('rejected', 'Rejected'), ('closed', 'Closed'), ('defaulted', 'Defaulted')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='members.member')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_disbursed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('principal_portion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interest_portion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('paid', models.BooleanField(default=False)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='finance.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_paid', models.DateTimeField(default=django.utils.timezone.now)),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='finance.loan')),
            ],
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='SMSTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('TOPUP', 'Top-up'), ('REMINDER', 'Arrears Reminder'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('disbursement', 'Loan Disbursement'), ('repayment', 'Loan Repayment'), ('penalty', 'Penalty')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('is_reversed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_created', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.loan')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='finance.chartofaccount')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='finance.transaction')),
            ],
            options={
                'verbose_name': 'General Ledger',
                'verbose_name_plural': 'General Ledger Entries',
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TransactionReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reversal_time', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('original_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reversal_details', to='finance.transaction')),
                ('reversed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
