# Generated by Django 6.0.4 on 2026-05-18 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyRepaymentSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("total_processed", models.PositiveIntegerField(default=0)),
                (
                    "total_recovered",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
                ),
                ("failed_deductions", models.PositiveIntegerField(default=0)),
                ("partial_payments", models.PositiveIntegerField(default=0)),
                ("closed_loans", models.PositiveIntegerField(default=0)),
                ("execution_duration_seconds", models.FloatField(default=0.0)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="AutoRepaymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "savings_balance_before",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "amount_attempted",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "amount_recovered",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Full Success"),
                            ("partial", "Partial Payment"),
                            ("failed", "Failed / Insufficient Funds"),
                            ("error", "System Execution Exception"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "installment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.installment",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repayment_logs",
                        to="finance.loan",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AutoRepaymentSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Enable Auto Repayments"
                    ),
                ),
                (
                    "execution_time",
                    models.TimeField(default="22:00:00", verbose_name="Execution Time"),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=10,
                    ),
                ),
                (
                    "grace_period_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Grace Period (Days)"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Auto Repayment Setting",
                "verbose_name_plural": "Auto Repayment Settings",
            },
        ),
    ]
