# Generated by Django 6.0.4 on 2026-05-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_dailyrepaymentsummary_autorepaymentlog_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="globalsettings",
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "Global Settings",
            },
        ),
        migrations.RemoveField(
            model_name="loan",
            name="collateral_description",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="collateral_type",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="collateral_value",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="contact_person",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="contact_phone",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="guarantor_1_name",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="guarantor_1_phone",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="guarantor_2_name",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="guarantor_2_phone",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="location",
        ),
        migrations.AlterField(
            model_name="loan",
            name="interest_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="loan",
            name="principal_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="loan",
            name="purpose",
            field=models.TextField(blank=True, null=True, verbose_name="Loan Purpose"),
        ),
        migrations.AlterField(
            model_name="loan",
            name="total_payable",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="enable_back_dating",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, manually set dates for deposits and repayments can be used.",
            ),
        ),
    ]
