# Generated by Django 6.0.4 on 2026-04-27 12:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_loan_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_paid', models.DateTimeField(default=django.utils.timezone.now)),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='finance.loan')),
            ],
        ),
    ]
