# Generated by Django 6.0.4 on 2026-04-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_repayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('disbursement', 'Loan Disbursement'), ('repayment', 'Loan Repayment'), ('penalty', 'Penalty')], max_length=20),
        ),
    ]
