# Generated by Django 6.0.4 on 2026-05-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_alter_globalsettings_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="collateral_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Collateral Details"
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="collateral_type",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Collateral Type"
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="collateral_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Estimated Collateral Value",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="contact_person",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Contact Person"
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                verbose_name="Contact Phone Number",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="guarantor_1_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Guarantor 1 Name"
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="guarantor_1_phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Guarantor 1 Phone"
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="guarantor_2_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Guarantor 2 Name"
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="guarantor_2_phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Guarantor 2 Phone"
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="location",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Business / Physical Location",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="interest_balance",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="principal_balance",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="purpose",
            field=models.TextField(
                blank=True, null=True, verbose_name="Loan Purpose / Description"
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="total_payable",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=12
            ),
        ),
    ]
