# Generated by Django 6.0.4 on 2026-06-17 08:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_loan_collateral_description_loan_collateral_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="generalledger",
            options={},
        ),
        migrations.AddField(
            model_name="installment",
            name="interest_paid",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="installment",
            name="penalty_paid",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="installment",
            name="principal_paid",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddIndex(
            model_name="generalledger",
            index=models.Index(
                fields=["date", "account"], name="finance_gen_date_f23b3a_idx"
            ),
        ),
    ]
