# Generated by Django 6.0.4 on 2026-06-17 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_alter_generalledger_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="installment",
            name="amount_remaining",
        ),
    ]
