# Generated by Django 6.0.4 on 2026-04-29 17:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_loan_disbursed_date_loan_officer_alter_loan_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='installment',
            old_name='amount',
            new_name='interest_portion',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='balance',
            new_name='interest_balance',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='penalty_rate',
        ),
        migrations.AddField(
            model_name='installment',
            name='principal_portion',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='principal_balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
