# Generated by Django 6.0.4 on 2026-06-30 10:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_remove_installment_amount_remaining"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loan",
            options={},
        ),
        migrations.AddField(
            model_name="loan",
            name="penalty_flat_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1000.00"),
                help_text="Used for flat penalties",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="penalty_grace_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="loan",
            name="penalty_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Used for percentage-based penalties",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="penalty_type",
            field=models.CharField(
                choices=[
                    ("daily_flat", "Daily Flat"),
                    ("daily_percentage", "Daily Percentage"),
                    ("fixed", "Fixed Penalty"),
                    ("compound", "Compound Penalty"),
                ],
                default="daily_flat",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="repayment_frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("manual", "Manual"),
                ],
                default="monthly",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="term_value",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of cycles depending on frequency (days/weeks/months)",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="collateral_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="collateral_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="collateral_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="loan",
            name="contact_person",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="guarantor_1_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="guarantor_1_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="guarantor_2_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="guarantor_2_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="interest_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="loan",
            name="interest_rate",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="loan",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="period_months",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="loan",
            name="principal_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="loan",
            name="purpose",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="total_payable",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name="LoanPenaltyRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "penalty_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed Amount"),
                            ("percentage", "Percentage of overdue"),
                            ("daily", "Daily penalty"),
                        ],
                        default="fixed",
                        max_length=20,
                    ),
                ),
                (
                    "fixed_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "percentage_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "daily_penalty_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("grace_period_days", models.PositiveIntegerField(default=0)),
                (
                    "max_penalty_cap",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="0 = unlimited",
                        max_digits=12,
                    ),
                ),
                (
                    "loan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="penalty_rule",
                        to="finance.loan",
                    ),
                ),
            ],
        ),
    ]
