# Generated by Django 6.0.4 on 2026-07-01 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_alter_loan_options_loan_penalty_flat_amount_and_more"),
        ("members", "0007_alter_member_card_number_alter_member_dob_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsetting",
            name="key",
            field=models.CharField(default="KAL", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="members.member",
            ),
        ),
    ]
