# Generated by Django 6.0.4 on 2026-04-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_rename_amount_installment_interest_portion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_reference',
            field=models.CharField(blank=True, help_text='Alphanumeric loan reference', max_length=20, null=True, unique=True),
        ),
    ]
