# Generated by Django 6.0.4 on 2026-04-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_loan_loan_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='amount_remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
