# Generated by Django 6.0.4 on 2026-07-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_systemsetting_key_systemsetting_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsetting",
            name="member_prefix",
            field=models.CharField(
                default="KAL",
                help_text="Prefix used for member numbers (e.g. KAL, ABC)",
                max_length=10,
            ),
        ),
    ]
