# Generated by Django 6.0.4 on 2026-07-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_systemsetting_member_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="accumulated_penalty",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="loan",
            name="last_penalty_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="penalty_frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="monthly",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="penalty_type",
            field=models.CharField(
                choices=[
                    ("daily_flat", "Daily Flat"),
                    ("daily_percentage", "Daily Percentage"),
                    ("fixed", "Fixed Penalty"),
                    ("compound", "Compound Penalty"),
                    ("monthly_once", "Monthly Once (on total due)"),
                ],
                default="daily_flat",
                max_length=25,
            ),
        ),
    ]
