# Generated by Django 6.0.4 on 2026-04-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_installment_amount_remaining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installment',
            name='amount_remaining',
        ),
        migrations.AlterField(
            model_name='installment',
            name='interest_portion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='installment',
            name='principal_portion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_reference',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='principal_balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_payable',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
