# Generated by Django 6.0.4 on 2026-04-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_remove_installment_amount_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='amount_remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
