# Generated by Django 6.0.4 on 2026-07-01 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0010_loan_accumulated_penalty_loan_last_penalty_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="accumulated_penalty",
        ),
    ]
