# Generated by Django 6.0.4 on 2026-04-30 09:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_installment_amount_remaining'),
        ('members', '0003_member_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Loan', 'verbose_name_plural': 'Loans'},
        ),
        migrations.AddField(
            model_name='loan',
            name='collateral_description',
            field=models.TextField(blank=True, null=True, verbose_name='Collateral Details'),
        ),
        migrations.AddField(
            model_name='loan',
            name='collateral_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Collateral Type (e.g., Land, Vehicle, House)'),
        ),
        migrations.AddField(
            model_name='loan',
            name='collateral_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Estimated Collateral Value'),
        ),
        migrations.AddField(
            model_name='loan',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Person (if different from member)'),
        ),
        migrations.AddField(
            model_name='loan',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Phone Number'),
        ),
        migrations.AddField(
            model_name='loan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantor_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guaranteed_loans_1', to='members.member', verbose_name='Guarantor 1'),
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantor_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guaranteed_loans_2', to='members.member', verbose_name='Guarantor 2'),
        ),
        migrations.AddField(
            model_name='loan',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Business / Physical Location'),
        ),
        migrations.AddField(
            model_name='loan',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='product_type',
            field=models.CharField(choices=[('personal', 'Personal Loan'), ('business', 'Business Loan'), ('salary', 'Salary Advance'), ('group', 'Group Loan'), ('emergency', 'Emergency Loan'), ('asset', 'Asset Finance')], default='personal', max_length=20, verbose_name='Loan Product'),
        ),
        migrations.AddField(
            model_name='loan',
            name='purpose',
            field=models.TextField(blank=True, null=True, verbose_name='Loan Purpose / Description'),
        ),
        migrations.AddField(
            model_name='loan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, help_text='Rate in percentage (e.g., 12.5)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_reference',
            field=models.CharField(blank=True, help_text='Unique alphanumeric loan reference (e.g., LN-ABC1234567)', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_disbursed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed'), ('defaulted', 'Defaulted')], default='pending', max_length=20),
        ),
    ]
