# Generated by Django 6.0.4 on 2026-04-30 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_loan_options_loan_collateral_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='guarantor_1',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='guarantor_2',
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantor_1_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Guarantor 1 Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantor_1_phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='Guarantor 1 Phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantor_2_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Guarantor 2 Name'),
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantor_2_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Guarantor 2 Phone'),
        ),
    ]
