# Generated by Django 6.0.4 on 2026-07-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "finance",
            "0012_alter_transaction_options_transaction_reversal_date_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="MAC Technologies", max_length=100)),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        default="Core Banking & Financial Services",
                        max_length=200,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="company/"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="+256 700 000 000", max_length=20
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="mmayambala@schooladmin.tech",
                        max_length=254,
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, default="www.schooladmin.tech"),
                ),
                ("address", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Company",
            },
        ),
    ]
