# Generated by Django 6.0.4 on 2026-07-16 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0013_company"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loan",
            options={
                "permissions": [
                    ("can_apply_loan", "Can apply for a loan"),
                    ("can_approve_loan", "Can approve a loan"),
                    ("can_disburse_loan", "Can disburse a loan"),
                    ("can_apply_manual_penalty", "Can manually apply penalty"),
                    ("can_waive_penalty", "Can waive penalties"),
                ]
            },
        ),
        migrations.RemoveField(
            model_name="loanpenaltyrule",
            name="daily_penalty_amount",
        ),
        migrations.AddField(
            model_name="loanpenaltyrule",
            name="compound",
            field=models.BooleanField(
                default=False,
                help_text="If True, penalty is calculated on principal+interest+previous penalty",
            ),
        ),
        migrations.AddField(
            model_name="loanpenaltyrule",
            name="override_applied_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="penalty_overrides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loanpenaltyrule",
            name="override_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanpenaltyrule",
            name="override_penalty",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="If set, this exact amount is used as penalty (manual override)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="loanpenaltyrule",
            name="period",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("weekly", "Weekly"),
                    ("daily", "Daily"),
                ],
                default="monthly",
                help_text="How often the penalty is applied (e.g., monthly for percentage)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="loan_reference",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="officer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="penalty_flat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="loan",
            name="penalty_frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="monthly",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="penalty_rate",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="loan",
            name="penalty_type",
            field=models.CharField(
                choices=[
                    ("daily_flat", "Daily Flat"),
                    ("daily_percentage", "Daily Percentage"),
                    ("fixed", "Fixed Penalty"),
                    ("compound", "Compound Penalty"),
                    ("monthly_once", "Monthly Once"),
                ],
                default="daily_flat",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("personal", "Personal Loan"),
                    ("business", "Business Loan"),
                    ("salary", "Salary Advance"),
                    ("group", "Group Loan"),
                    ("emergency", "Emergency Loan"),
                    ("asset", "Asset Finance"),
                ],
                default="personal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="term_value",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="loanpenaltyrule",
            name="fixed_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Used for fixed or daily_flat",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="loanpenaltyrule",
            name="grace_period_days",
            field=models.PositiveIntegerField(
                default=0, help_text="Days after due date before penalty starts"
            ),
        ),
        migrations.AlterField(
            model_name="loanpenaltyrule",
            name="max_penalty_cap",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Maximum penalty per period (0 = unlimited)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="loanpenaltyrule",
            name="penalty_type",
            field=models.CharField(
                choices=[
                    ("fixed", "Fixed amount per period"),
                    ("percentage", "Percentage of overdue amount per period"),
                    ("daily_flat", "Daily flat amount"),
                    ("daily_percentage", "Daily percentage of overdue amount"),
                ],
                default="percentage",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="loanpenaltyrule",
            name="percentage_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Percentage rate (e.g., 5 for 5%)",
                max_digits=5,
            ),
        ),
        migrations.CreateModel(
            name="ManualPenalty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("reason", models.TextField()),
                ("applied_date", models.DateTimeField(auto_now_add=True)),
                ("is_waived", models.BooleanField(default=False)),
                ("waived_date", models.DateTimeField(blank=True, null=True)),
                ("waiver_reason", models.TextField(blank=True, null=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manual_penalties_applied",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "installment",
                    models.ForeignKey(
                        blank=True,
                        help_text="If provided, penalty applies to this specific installment; otherwise to the entire loan balance",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.installment",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_penalties",
                        to="finance.loan",
                    ),
                ),
                (
                    "waived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="penalties_waived",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    (
                        "can_apply_manual_penalty",
                        "Can manually apply penalty to a loan",
                    ),
                    ("can_waive_penalty", "Can waive penalties"),
                ],
            },
        ),
    ]
