# Generated by Django 6.0.4 on 2026-05-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_remove_loan_guarantor_1_remove_loan_guarantor_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('arrears', 'In Arrears'), ('rejected', 'Rejected'), ('closed', 'Closed'), ('defaulted', 'Defaulted')], default='pending', max_length=20),
        ),
    ]
