# Generated by Django 6.0.4 on 2026-07-16 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0014_alter_loan_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manualpenalty",
            options={},
        ),
        migrations.AlterField(
            model_name="manualpenalty",
            name="installment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manual_penalties",
                to="finance.installment",
            ),
        ),
        migrations.AlterField(
            model_name="manualpenalty",
            name="waived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manual_penalties_waived",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
