# Generated by Django 6.0.4 on 2026-07-17 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0015_alter_manualpenalty_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="installment",
            name="penalty_waived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="installment",
            name="penalty_waived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="waived_penalties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="installment",
            name="penalty_waived_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="installment",
            name="penalty_waiver_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
