# Generated by Django 6.0.4 on 2026-05-12 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_alter_transaction_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TransactionReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reversal_time', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('original_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reversal_details', to='finance.transaction')),
                ('reversed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
