# Generated by Django 6.0.4 on 2026-07-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0016_installment_penalty_waived_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("disbursement", "Loan Disbursement"),
                    ("repayment", "Loan Repayment"),
                    ("penalty", "Penalty"),
                    ("reversal", "Reversal"),
                    ("journal", "Journal Entry"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
