# Generated by Django 6.0.4 on 2026-07-23 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0017_alter_transaction_type"),
        ("members", "0007_alter_member_card_number_alter_member_dob_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loan",
            options={
                "permissions": [
                    ("can_apply_loan", "Can apply for a loan"),
                    ("can_approve_loan", "Can approve a loan"),
                    ("can_disburse_loan", "Can disburse a loan"),
                    ("can_apply_manual_penalty", "Can manually apply penalty"),
                    ("can_waive_penalty", "Can waive penalties"),
                    ("can_send_sms", "Can send SMS reminders"),
                ]
            },
        ),
        migrations.AlterField(
            model_name="transaction",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="members.member",
            ),
        ),
    ]
