# Generated by Django 6.0.4 on 2026-05-12 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_transaction_created_by_transaction_is_reversed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.loan'),
        ),
    ]
