# Generated by Django 6.0.4 on 2026-05-13 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0018_transaction_loan"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chartofaccount",
            options={"ordering": ["code"], "verbose_name": "Chart of Account"},
        ),
        migrations.AlterModelOptions(
            name="generalledger",
            options={
                "ordering": ["date", "id"],
                "verbose_name": "General Ledger",
                "verbose_name_plural": "General Ledger Entries",
            },
        ),
        migrations.AlterField(
            model_name="generalledger",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries",
                to="finance.chartofaccount",
            ),
        ),
        migrations.AlterField(
            model_name="generalledger",
            name="reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="generalledger",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="finance.transaction",
            ),
        ),
    ]
