# Generated by Django 6.0.8 on 2026-09-08 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_alter_loan_options_alter_transaction_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': [('can_access_settings', 'Can access system settings')], 'verbose_name': 'Company', 'verbose_name_plural': 'Company'},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'permissions': [('can_apply_loan', 'Can apply for a loan'), ('can_approve_loan', 'Can approve a loan'), ('can_disburse_loan', 'Can disburse a loan'), ('can_apply_manual_penalty', 'Can manually apply penalty'), ('can_waive_penalty', 'Can waive penalties'), ('can_send_sms', 'Can send SMS reminders'), ('can_access_settings', 'Can access system settings')]},
        ),
    ]
