# Generated by Django 6.0.4 on 2026-05-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0019_alter_chartofaccount_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chartofaccount",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
