# Generated by Django 6.0.8 on 2026-09-08 09:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_alter_company_options_alter_loan_options'),
        ('members', '0008_userprofile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='marzpay_response',
            field=models.JSONField(blank=True, help_text='Full raw response from MarzPay', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque')], default='CASH', help_text='Payment method used', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_reference',
            field=models.CharField(blank=True, db_index=True, help_text='External payment gateway reference (e.g., MarzPay transaction ID)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for mobile money', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled')], db_index=True, default='completed', help_text='Transaction lifecycle status', max_length=20),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='finance_tra_status_0941b9_idx'),
        ),
    ]
