# Generated by Django 6.0.4 on 2026-05-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_chartofaccount_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_global_2fa', models.BooleanField(default=True, help_text='If checked, all users must verify via 2FA. If unchecked, 2FA is skipped.', verbose_name='Enable Global 2FA')),
            ],
            options={
                'verbose_name': 'Global Setting',
                'verbose_name_plural': 'Global Settings',
            },
        ),
    ]
