# Generated by Django 6.0.4 on 2026-05-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_globalsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='collateral_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Collateral Type'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, help_text='Percentage rate (e.g., 12.5)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='enable_back_dating',
            field=models.BooleanField(default=False, help_text='If enabled, Manually set dates for deposits and repayments can be used.'),
        ),
    ]
