# Generated by Django 6.0.4 on 2026-07-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="current_stock",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
