# Generated by Django 6.0.8 on 2026-09-08 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_product_current_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='marzpay_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('failed', 'Payment Failed'), ('cancelled', 'Cancelled')], default='paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.customer'),
        ),
    ]
