"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 5.1.1.
"""

from pathlib import Path
import os
from decouple import config

# ==========================================
# BASE DIRECTORY
# ==========================================

BASE_DIR = Path(__file__).resolve().parent.parent

# ==========================================
# SECURITY SETTINGS
# ==========================================

DEBUG = True

SECRET_KEY = config(
    'SECRET_KEY',
    default='django-insecure-change-this-in-production'
)

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
]
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'

# Safety guardrails discussed earlier
CELERY_TASK_ACKS_LATE = False
CELERY_TASK_TIME_LIMIT = 1800
# ==========================================
# APPLICATION DEFINITION
# ==========================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # Third Party Extensions
    'rest_framework',          # <--- Crucial Addition: Resolves the import exception

    # Your Apps
    'members',
    'finance',
    'hardware',
    'notifications',

    # 2FA Apps
    'django_otp',
    'django_otp.plugins.otp_static',
    'django_otp.plugins.otp_totp',
    'two_factor',
    'widget_tweaks',
    'django_celery_beat',
]

# ==========================================
# MIDDLEWARE
# ==========================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    # OTP Middleware
    'django_otp.middleware.OTPMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Custom Middleware
    'members.middleware.LoginRequiredMiddleware',
]

# ==========================================
# URLS & WSGI
# ==========================================


ROOT_URLCONF = 'credit.urls'

WSGI_APPLICATION = 'credit.wsgi.application'

# ==========================================
# TEMPLATES
# ==========================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # Custom Context Processors
                'finance.context_processors.sacco_stats',
                'notifications.context_processors.notifications',
                'members.context_processors.module_permissions',
                'finance.context_processors.company_context',
            ],
        },
    },
]

# ==========================================
# DATABASE
# ==========================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',

        # FOR PRODUCTION USE MYSQL/POSTGRESQL
        # 'ENGINE': config('DB_ENGINE'),
        # 'NAME': config('DB_NAME'),
        # 'USER': config('DB_USER'),
        # 'PASSWORD': config('DB_PASSWORD'),
        # 'HOST': config('DB_HOST'),
        # 'PORT': config('DB_PORT'),
    }
}

# ==========================================
# REST FRAMEWORK EXPLICIT SETTINGS
# ==========================================
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
}

# ==========================================
# PASSWORD VALIDATORS
# ==========================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ==========================================
# BULK IMPORT MODE
# ==========================================

BULK_IMPORT_MODE = True

# ==========================================
# INTERNATIONALIZATION
# ==========================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Kampala'

USE_I18N = True

USE_TZ = True

# ==========================================
# STATIC FILES
# ==========================================

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# ==========================================
# MEDIA FILES
# ==========================================

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ==========================================
# LOGIN / LOGOUT
# ==========================================

LOGIN_URL = 'auth/login/'
LOGOUT_REDIRECT_URL = 'auth/login/'

# ==========================================
# SESSION & SECURITY SETTINGS
# ==========================================

# Development Settings
# SESSION_COOKIE_SECURE = False
# CSRF_COOKIE_SECURE = False

# SESSION_COOKIE_HTTPONLY = True
# CSRF_COOKIE_HTTPONLY = True

# SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# SESSION_SAVE_EVERY_REQUEST = False

# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True

# ==========================================
# EMAIL SETTINGS
# ==========================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587

EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')

EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# ==========================================
# WEBSITE SETTINGS
# ==========================================

WEBSITE_URL = 'https://saozirobwe.co.ug'

# ==========================================
# DEFAULT PRIMARY KEY
# ==========================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'