# Generated by Django 6.0.4 on 2026-04-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/')),
                ('id_front', models.ImageField(blank=True, null=True, upload_to='members/ids/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='members/signatures/')),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
