# Generated by Django 6.0.4 on 2026-04-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['member_number']},
        ),
        migrations.AddField(
            model_name='member',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Alternative Phone Number'),
        ),
        migrations.AddField(
            model_name='member',
            name='card_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Membership Card Number'),
        ),
        migrations.AddField(
            model_name='member',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='nin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='National ID Number (NIN)'),
        ),
        migrations.AddField(
            model_name='member',
            name='parish',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='physical_address',
            field=models.TextField(blank=True, null=True, verbose_name='Physical Address / Residence'),
        ),
        migrations.AddField(
            model_name='member',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
