# Generated by Django 6.0.4 on 2026-07-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_module_userprofile_allowed_modules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="card_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="nin",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
