# Generated by Django 6.0.4 on 2026-07-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_alter_member_card_number_alter_member_dob_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="profile_pics/"
            ),
        ),
    ]
